-- MySQL Script generated by MySQL Workbench
-- Tue Dec 16 17:03:04 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mouvinsa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mouvinsa` ;

-- -----------------------------------------------------
-- Schema mouvinsa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mouvinsa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mouvinsa` ;