-- MySQL Script generated by MySQL Workbench
-- Tue Dec 16 17:03:04 2014
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mouvinsa
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mouvinsa` ;

-- -----------------------------------------------------
-- Schema mouvinsa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mouvinsa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mouvinsa` ;

-- -----------------------------------------------------
-- Table `mouvinsa`.`Goal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Goal` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Goal` (
  `idGoal` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `difficulty` ENUM('difficile','moyen','facile') NULL,
  `label` VARCHAR(45) NULL,
  `distance` INT NULL,
  `image` VARCHAR(45) NULL,
  PRIMARY KEY (`idGoal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Group` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Group` (
  `idGroup` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(100) NULL,
  `slogan` VARCHAR(255) NULL,
  `stepSum` INT UNSIGNED NULL,
  `image` VARCHAR(255) NULL,
  `idGoal` INT UNSIGNED NULL,
  PRIMARY KEY (`idGroup`),
  INDEX `group_goal` (`idGoal` ASC),
  CONSTRAINT `group_goal`
    FOREIGN KEY (`idGoal`)
    REFERENCES `mouvinsa`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Person` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Person` (
  `idPerson` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idGroup` INT UNSIGNED NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `sex` CHAR NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `birthdate` DATETIME NULL,
  `weight` FLOAT NULL COMMENT '	',
  `height` FLOAT NULL,
  `category` ENUM('STUDENT','IATOS','EMPLOYEE') NULL,
  `image` VARCHAR(255) NULL,
  `etat` ENUM('PREREGISTERED','REGISTERED', 'DROPPED') NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC),
  PRIMARY KEY (`idPerson`),
  INDEX `idGroup` (`idGroup` ASC),
  CONSTRAINT `personGroup`
    FOREIGN KEY (`idGroup`)
    REFERENCES `mouvinsa`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Student` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Student` (
  `idStudent` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPerson` INT UNSIGNED NOT NULL,
  `year` TINYINT NULL,
  `cycle` ENUM('FIRST','SECOND') NULL,
  `branch` ENUM('EURINSA', 'AMERINSA', 'ASINSA', 'SCAN', 'BB - Biochimie et Biotechnologies' , 'BIM - BioInformatique et Modélisation' , 'GCU - Génie civil et urbanisme' , 'GE - Génie électrique' , 'GEN - Génie énergétique et environnement' , 'GMC - Génie mécanique conception' , 'GMD - Génie mécanique développement' , 'GMPP - Génie mécanique procédés plasturgie' , 'GI - Génie Industriel' , 'IF - Informatique' , 'SGM - Science et Génie des Matériaux' , 'TC - Télécommunications Services et Usages', 'GMPPA - Génie Mécanique Procédés Plasturgie', 'GMCIP - Génie Mécanique Conception et Innovation de Produits', 'GEAL - Génie Electrique' , 'TCA - Télécommunications') NULL,
  PRIMARY KEY (`idStudent`),
  INDEX `idPerson` (`idPerson` ASC),
  CONSTRAINT `studentPerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Employee` (
  `idEmployee` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPerson` INT UNSIGNED NOT NULL,
  `affiliation` VARCHAR(255) NULL,
  `position` VARCHAR(255) NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `idPerson` (`idPerson` ASC),
  CONSTRAINT `employeePerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`FitnessInfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`FitnessInfo` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`FitnessInfo` (
  `idFitnessInfo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPerson` INT UNSIGNED NOT NULL,
  `stepSum` VARCHAR(45) NULL,
  `streak` INT UNSIGNED NULL,
  `bestStreak` INT NULL,
  `goal` VARCHAR(45) NULL,
  PRIMARY KEY (`idFitnessInfo`),
  INDEX `idPerson` (`idPerson` ASC),
  CONSTRAINT `fitnessInfoPerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`steps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`steps` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`steps` (
  `idsteps` INT NOT NULL AUTO_INCREMENT,
  `idPerson` INT UNSIGNED NOT NULL,
  `date` DATETIME NULL COMMENT '	',
  `stepnumber` INT NULL,
  PRIMARY KEY (`idsteps`),
  INDEX `idPerson` (`idPerson` ASC),
  INDEX `date` (`date` ASC),
  CONSTRAINT `stepsPerson`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Badge`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Badge` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Badge` (
  `idBadge` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(128) NULL,
  `description` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  PRIMARY KEY (`idBadge`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`badge_person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`badge_person` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`badge_person` (
  `idBadge` INT UNSIGNED NOT NULL,
  `IdPerson` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idBadge`, `IdPerson`),
  INDEX `idBadge` (`idBadge` ASC),
  INDEX `idPerson` (`IdPerson` ASC),
  CONSTRAINT `badgePerson`
    FOREIGN KEY (`IdPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Personbadge`
    FOREIGN KEY (`idBadge`)
    REFERENCES `mouvinsa`.`Badge` (`idBadge`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`City` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`City` (
  `idCity` INT UNSIGNED NOT NULL,
  `label` VARCHAR(127) NULL,
  `distanceFromLyon` INT NULL COMMENT '	',
  `picture` VARCHAR(255) NULL,
  `caption` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`idCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Goal_city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Goal_city` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Goal_city` (
  `idGoal` INT UNSIGNED NOT NULL,
  `idCity` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idGoal`, `idCity`),
  INDEX `city_goal_idx` (`idCity` ASC),
  CONSTRAINT `goal_city`
    FOREIGN KEY (`idGoal`)
    REFERENCES `mouvinsa`.`Goal` (`idGoal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `city_goal`
    FOREIGN KEY (`idCity`)
    REFERENCES `mouvinsa`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`Messages` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`Messages` (
  `idMessages` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `idPerson` INT UNSIGNED NOT NULL,
  `idGroup` INT UNSIGNED NOT NULL,
  `message` TEXT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`idMessages`),
  INDEX `message_person` (),
  INDEX `message_group` (),
  INDEX `message_person_idx` (`idPerson` ASC),
  INDEX `message_group_idx` (`idGroup` ASC),
  CONSTRAINT `message_person`
    FOREIGN KEY (`idPerson`)
    REFERENCES `mouvinsa`.`Person` (`idPerson`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `message_group`
    FOREIGN KEY (`idGroup`)
    REFERENCES `mouvinsa`.`Group` (`idGroup`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`VIP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`VIP` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`VIP` (
  `idVIP` INT NOT NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`idVIP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mouvinsa`.`AdminEvents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mouvinsa`.`AdminEvents` ;

CREATE TABLE IF NOT EXISTS `mouvinsa`.`AdminEvents` (
  `idAdminEvent` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `label` VARCHAR(45) NULL,
  `startDate` DATETIME NULL,
  `endDate` DATETIME NULL,
  `active` TINYINT(1) NULL,
  PRIMARY KEY (`idAdminEvent`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
